stages:
- quality
- deploy
- set-webhook

unit-testing:
  stage: quality
  image: python:3.10-slim
  script:
    - pip install -r requirements.txt
    - python3 -m unittest

deploy-cloud-function:
  stage: deploy
  image: google/cloud-sdk
  script:
    - echo $GCP_ACCOUNT_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud functions deploy $GCF_NAME
      --runtime=python310 
      --entry-point=main
      --set-env-vars APP_TOKEN=$APP_TOKEN,CHANNEL_ID=$CHANNEL_ID,LOG_CHAT_ID=$LOG_CHAT_ID,GITLAB_API_TOKEN=$GITLAB_API_TOKEN,REPOSITORY_BASE_URL=$REPOSITORY_BASE_URL,TG_POST_FILE_PATH=$TG_POST_FILE_PATH,BOT_TOKEN=$BOT_TOKEN
      --region=europe-west1
      --trigger-http
      --allow-unauthenticated
      --source=.
    - echo "WEBHOOK_URL=$(gcloud functions describe --region=europe-west1 $GCF_NAME | grep -Po "url.+?\K(\S+)" | grep $GCF_NAME)" >> deploy.env
  artifacts:
    reports:
      dotenv: deploy.env
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

set-webhook:
  stage: set-webhook
  image: python:3.10-slim
  variables:
    BOT_TOKEN: $BOT_TOKEN
  script:
    - pip install -r requirements.txt
    - python3 -m set_webhook
