stages:
- quality
- deploy

unit-testing:
  stage: quality
  image: python:3.10-slim
  script:
    - pip install -r requirements.txt
    - python3 -m unittest

deploy-cloud-function:
  stage: deploy
  image: google/cloud-sdk
  script:
    - echo $GCP_ACCOUNT_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud functions deploy $GCF_NAME
      --runtime=python310 
      --entry-point=main
      --region=europe-west1
      --source=.
      --trigger-http
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
